### ISSUE TITLE
Suggestion: Create a "Update all prices" button.

### ISSUE THREAD

**Issue by michiel2304** [hunterjm/fifa-autobuyer#103]
When you run the bot for a long time or when you have a lot of players in your list. 
Prices sometimes change, it would be good to update prices with one click.

Then you will not use an old lowest BIN and spam buy players for to much because they are all below that initial lowest BIN, but that price has dropped below the prices you buy players.

**Comment by yousufm5** [comment]
great idea i found that when running my bot it would buy players for an old lowest BIN would really improve the bot if this feature was added.

**Comment by hunterjm** [comment]
Prices are updated automatically every hour. If you restart the bot and prices for players haven't been updated, it will search them.

The bug with buying players for the old price settings was fixed in v0.3.1
