### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by alexeyvolodin** [hunterjm/fifa-autobuyer#11]
I have some problem with starting program. 

> `****@********:/var/js_fut/fifa-autobuyer-master# nvm exec 6.1 npm run dev
> Running node v6.1.0 (npm v3.8.6)
> 
> > fifa-autobuyer-webpack@0.10.0 dev /var/js_fut/fifa-autobuyer-master
> > concurrently --kill-others "npm run hot-server" "npm run start-hot"
> 
> [1]
> [1] > fifa-autobuyer-webpack@0.10.0 start-hot /var/js_fut/fifa-autobuyer-master
> [1] > cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development
> [1]
> [0]
> [0] > fifa-autobuyer-webpack@0.10.0 hot-server /var/js_fut/fifa-autobuyer-master
> [0] > cross-env NODE_ENV=development node -r babel-register server.js
> [0]
> [1] fs.js:634
> [1]   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
> [1]                  ^
> [1]
> [1] Error: ENOENT: no such file or directory, open '/var/js_fut/fifa-autobuyer-master/node_modules/electron/path.txt'
> [1]     at Error (native)
> [1]     at Object.fs.openSync (fs.js:634:18)
> [1]     at Object.fs.readFileSync (fs.js:502:33)
> [1]     at Object.<anonymous> (/var/js_fut/fifa-autobuyer-master/node_modules/electron/index.js:4:42)
> [1]     at Module._compile (module.js:541:32)
> [1]     at Object.Module._extensions..js (module.js:550:10)
> [1]     at Module.load (module.js:456:32)
> [1]     at tryModuleLoad (module.js:415:12)
> [1]     at Function.Module._load (module.js:407:3)
> [1]     at Module.require (module.js:466:17)
> [1]
> [1] npm
> [1]
> [1] ERR!
> [1]  Linux 3.16.0-4-amd64
> [1] npm
> [1]
> [1] ERR!
> [1]
> [1] argv
> [1]  "/root/.nvm/versions/node/v6.1.0/bin/node" "/var/js_fut/fifa-autobuyer-master/node_modules/.bin/npm" "run" "start-hot"
> [1] npm ERR! node v6.1.0
> [1] npm ERR! npm  v3.10.8
> [1] npm ERR! code ELIFECYCLE
> [1] npm ERR! fifa-autobuyer-webpack@0.10.0 start-hot: `cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development`
> [1] npm ERR!
> [1]  Exit status 1
> [1] npm ERR!
> [1] npm ERR! Failed at the fifa-autobuyer-webpack@0.10.0 start-hot script 'cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development'.
> [1] npm ERR! Make sure you have the latest version of node.js and npm installed.
> [1] npm ERR! If you do, this is most likely a problem with the fifa-autobuyer-webpack package,
> [1] npm ERR! not with npm itself.
> [1] npm ERR! Tell the author that this fails on your system:
> [1] npm ERR!     cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development
> [1] npm ERR! You can get information on how to open an issue for this project with:
> [1] npm ERR!     npm bugs fifa-autobuyer-webpack
> [1] npm ERR! Or if that isn't available, you can get their info via:
> [1] npm ERR!     npm owner ls fifa-autobuyer-webpack
> [1] npm ERR! There is likely additional logging output above.
> [1]
> [1] npm
> [1]
> [1] ERR!
> [1]  Please include the following file with any support request:
> [1] npm
> [1]
> [1] ERR!
> [1]      /var/js_fut/fifa-autobuyer-master/npm-debug.log
> [1] npm run start-hot exited with code 1
> --> Sending SIGTERM to other processes..
> [0] npm run hot-server exited with code null
> 
> npm ERR! Linux 3.16.0-4-amd64
> npm ERR! argv "/root/.nvm/versions/node/v6.1.0/bin/node" "/root/.nvm/versions/node/v6.1.0/bin/npm" "run" "dev"
> npm ERR! node v6.1.0
> npm ERR! npm  v3.8.6
> npm ERR! code ELIFECYCLE
> npm ERR! fifa-autobuyer-webpack@0.10.0 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the fifa-autobuyer-webpack@0.10.0 dev script 'concurrently --kill-others "npm run hot-server" "npm run start-hot"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the fifa-autobuyer-webpack package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     concurrently --kill-others "npm run hot-server" "npm run start-hot"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs fifa-autobuyer-webpack
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls fifa-autobuyer-webpack
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /var/js_fut/fifa-autobuyer-master/npm-debug.log
> `

**Comment by hunterjm** [comment]
sounds like you haven't done an `npm install`

**Comment by alexeyvolodin** [comment]
Sorry, but i'm done `npm install`. And i don't understand, why server don't start

**Comment by hunterjm** [comment]
Why are you running the server command with `nvm exec 6.1 npm run dev`?

Try:
```
rm -rf node_modules/
nvm use 6.1.0
npm install
npm run dev
```

**Comment by alexeyvolodin** [comment]
I tried this commands, but error repeated. I think maybe change port in application? Where i can do it?

**Comment by hunterjm** [comment]
Your error is this: `ENOENT: no such file or directory, open '/var/js_fut/fifa-autobuyer-master/node_modules/electron/path.txt'`

Does the file exist?

**Comment by alexeyvolodin** [comment]
Yes, this file exist in node_modules/electron folder.

**Comment by alexeyvolodin** [comment]
content of this file 
`dist/electron`

**Comment by hunterjm** [comment]
If the file exists it has to be a file permissions issue. Why do you have it in`/var`? What OS are you on?

**Comment by alexeyvolodin** [comment]
Debian.
I can move this project to home directory.

**Comment by alexeyvolodin** [comment]
`dist/electron` permission is 755

**Comment by alexeyvolodin** [comment]
I moved project to home directory, remove node_modules, reinstall and have same error. :(

**Comment by hunterjm** [comment]
I unfortunately don't have access to a Linux box to help debug. It builds and runs fine on my Mac. The project is still in development and isn't fully functional at this time.

You could try running my other project futgui, which does work currently, but won't look as nice.

**Comment by alexeyvolodin** [comment]
Okay, thanks.
I'm already use your `futgui` project.
