### ISSUE TITLE
Bought players don't get listed.

### ISSUE THREAD

**Issue by Bob930** [hunterjm/fifa-autobuyer#114]
I have set a player to be bought for 350 and sold for 450. The programm somehow doesn't list the player after it wins a bid.

**Comment by Fotospecht** [comment]
Which player exactly ?

**Comment by mestesso93** [comment]
i've got same issues. I think that cause is last update. Simply the bidder win the auction and automatically send players to "unassigned" but the AB doesn't sign in the box "unassigned". I can view this player only with web-app

**Comment by hunterjm** [comment]
Duplicate of #98

**Comment by Bob930** [comment]
hunterjm, this isn't a duplicate to issue #98. The players that it has won through bidding just stay in the "bidding section" and don't even get sent to unassigned.
