### ISSUE TITLE
New TOTW appears as "Unknown"

### ISSUE THREAD

**Issue by mestesso93** [hunterjm/fifa-autobuyer#115]
I've set the AB on a new player of TOTW. If i check the log, the name appear. But if i check BUYING, SELLING, UNASSIGNED, this player appear as "unknown"

**Comment by hunterjm** [comment]
Duplicate of #52

**Comment by mestesso93** [comment]
ops, sorry

**Comment by hunterjm** [comment]
No problem. I just try and keep the issues clean because I use them to determine what to do next (when i have a couple hours to spare)
