### ISSUE TITLE
Bought players don't get listed

### ISSUE THREAD

**Issue by Bob930** [hunterjm/fifa-autobuyer#117]
I have set a player to be bought for 350 and sold for 450. The programm somehow doesn't list the player after it wins a bid. The player just stays in the active transfers window with a expiry -1. They don't even get sent to unassigned. This isn't a duplicate of issue #98

**Comment by Fotospecht** [comment]
Could you check if this happens with Rincon / Juventus version ?

**Comment by hunterjm** [comment]
Let's keep track of this in #130.
