### ISSUE TITLE
Can't BIN snipe a single player?

### ISSUE THREAD

**Issue by frayzee** [hunterjm/fifa-autobuyer#120]
I've been using the AB for a couple of weeks now and the bidding part of the AB works very well however the problem I have is when I set it to BIN snipe only I've never won a single player, I've got a solid fibre internet connection and run some tests that shows I have a good ping to the EA servers.

Has anybody else had this problem? I feel Like the AB has a delay between searching for the player and the BIN snipe meaning it never tries to snipe bang on that golden 1hr mark.

**Comment by hunterjm** [comment]
There is a delay based on your RPM between searching and sniping.  This is to make the AB seem human and help prevent bans.  If your RPM is 10, the AB won't place a bid on the found player for 5-7 seconds after the search is complete.  If you want to snipe, you should increase the RPM and run the AB for a shorter period of time.

The magic formula is `4000/60/{RPM}` which gives you how many hours you can run the program at a given RPM without much worry of a temp ban.  After running it for that time, wait 24 hours before running again.
