### ISSUE TITLE
In a span of 24 hours

### ISSUE THREAD

**Issue by edenhazard7** [hunterjm/fifa-autobuyer#127]
How many hours can I use the autobuyer? and in chunks of how many hours?
Thanks!

**Comment by WillowWillowWillow** [comment]
It all depends on your RPM. If you have it set to 7, run it for about 7-9 hours. 

 8 rpm, 6-8 hours | 9 rpm 5.5-7.5 | and at 10 RPM I would only recommend to run it for about 5 hours, as most people usually get multiple "500 errors" around that time

**Comment by edenhazard7** [comment]
Thanks, will run it for four hours a day at 10 RPM! If its not too much to ask, what % do u set the auto bid, sell and bin to?
 I used 95, 100, 105 with Joao Moutinho but he wouldn't sell.
 Thanks!

**Comment by mestesso93** [comment]
to sell a player, you must choose one very popular (like musa?) or a player helpful to sbc. At the moment a good player is pedro, but there is a very high risk. Bid to player helpful to sbc!
