### ISSUE TITLE
my Autobuyer has stopped working!!!

### ISSUE THREAD

**Issue by Benglennon123** [hunterjm/fifa-autobuyer#129]
Hi woke up this morning, started the update and found that my program has stopped working. It can never find the players prices. I have unistalled and re-installed many times is there any other fixes.
Thanks, Ben
#125

**Comment by hunterjm** [comment]
No need to uninstall or anything. Probably was running too long and got a temp ban. Try again in 12 hours or so.

**Comment by Benglennon123** [comment]
Okay thanks , Think your right anyway to automate how long it runs for and make it take breaks periodically?

**Comment by hunterjm** [comment]
You can set the auto stop setting to determine how long it runs. Basically you can make 4000 requests in 24 hours. I would set your RPM and your Auto Stop to reflect that, depending on how long you want it to run.

**Comment by Benglennon123** [comment]
Any advice on wheat players work best?

**Comment by Benglennon123** [comment]
Hi I've recently had my account banned im not angry or nothing just wished
to inform you so you know there is an issue here, anyway i can get this
coins back though ?
