### ISSUE TITLE
how this is work ?

### ISSUE THREAD

**Issue by moathabdulhadi** [hunterjm/fifa-autobuyer#13]
hello @hunterjm 

thank you for your effort , its really great

but i install it and open it , it request you know , email password and everything 
and it's open . now i can search for player , but after that ? what should i do , like if i want only to snipe?

how to make it like that

thank you again

**Comment by hunterjm** [comment]
This version is still in development and not yet fully functional. For a working auto buyer, look at hunterjm/futgui
