### ISSUE TITLE
Cards that have multiple versions seem to stay in unassigned.

### ISSUE THREAD

**Issue by michiel2304** [hunterjm/fifa-autobuyer#130]
I was trading with Sakho, who has a Crystal Palace card and a Liverpool version.
The autobuyer buys the right version, the one i selected, but it does not sell it for some odd reason.

Any idea how to solve this problem?

**Comment by Fotospecht** [comment]
Same problem here with Rincon.

**Comment by Daves10** [comment]
This is what i meant in #70 !

**Comment by mestesso93** [comment]
cards purchased with bin price too!

**Comment by hunterjm** [comment]
Does the player show up as "Unknown" after it buys it in the "Overview" tab?

**Comment by Gsoul2k9** [comment]
yes shown as Unknown

**Comment by mestesso93** [comment]
with bin price them they're not appear in AB but only with login into web-app in the "unassigned"

**Comment by Bob930** [comment]
It's only happening with players who have a 2 cards. One at one club and one at another. I hope this is helpfull.

**Comment by Bob930** [comment]
Oops, ignore this previous comment please.

**Comment by hunterjm** [comment]
I think I've got this fixed in the upcoming v0.4.2 release.  Will let you know when live.

**Comment by hunterjm** [comment]
Release is live. Let me know if it fixes your issues.

**Comment by hunterjm** [comment]
@mestesso93 - that is a different issue.  See #137.

**Comment by hunterjm** [comment]
Closing, as I have not heard anything in a while.

**Comment by michiel2304** [comment]
For me it is fixed in the latest version.
