### ISSUE TITLE
The bot takes a long time to list players bought

### ISSUE THREAD

**Issue by TonDanone** [hunterjm/fifa-autobuyer#137]
The bot takes a long time to list players bought, this causes loss of coins because when it will list, prices have already fallen a lot, Causing losses, Remembering that this delay problem occurs only for players bought in buy now, players bought in the bid are listed quickly in my case, I hope they solve because I see that the developer has done a beautiful job so far, thank you and sorry Poor English.

**Comment by hunterjm** [comment]
I think I may have a fix for this in the works.  I'm going to hold off on releasing until I get a couple more changes ready though.

**Comment by TonDanone** [comment]
In my opinion this is the biggest problem of the bot, when it is solved the profits will increase and the losses of currencies will be greatly reduced, thanks for the work one more time, I await news.

**Comment by hunterjm** [comment]
Let me know if you've still got an issue with the latest release: https://github.com/hunterjm/fifa-autobuyer/releases/tag/v0.4.3
