### ISSUE TITLE
Definitive ban

### ISSUE THREAD

**Issue by devmeireles** [hunterjm/fifa-autobuyer#146]
After two weeks using the app i made a profit from 80k but EA banned my account

![image](https://cloud.githubusercontent.com/assets/1919508/23064162/81d3b8b0-f4f5-11e6-92fb-93027bac5749.png)

**Comment by JON-GAMES** [comment]
This happened to me. Do you speak Portuguese BR? I'll explain how I got my account back.

**Comment by gmeireles** [comment]
@JON-GAMES Falo português brasileiro sim, por favor, pode me dar uma força?

**Comment by edenhazard7** [comment]
How much RPM for how long did you use?

**Comment by gmeireles** [comment]
@edenhazard7 i used preconfigured RPM 10 but in my player list i had 5 players
For this reason maybe RPM would be 50

**Comment by hunterjm** [comment]
@gmeireles did you use the auto stop functionality to stop bidding after 6 hours at 10 RPM, or did you run 24/7 and get lots of temporary bans before the permanent ban occurred?

**Comment by gmeireles** [comment]
@hunterjm i run 27 8 hour per day without interruptions
I believe it's permanent I have not yet accessed my console

**Comment by JON-GAMES** [comment]
Então. Recebi o mesmo Ban enquanto utilizava o AB fUTGUI ANTERIOR A ESTE.
O que eu fiz foi enviar e-mail para lets_talk@ea.com perguntando pq tinha sido banido...basicamente apelei para a cara de pau. Liguei na EA e falei com alguns representantes dizendo que não sabia e que eu apenas fazia trade e jogava. Depois de uns dias minha conta foi desbloqueada....Ai fiquei umas semanas sem usar o AB. Qualquer coisa chamar no zap que te mostro como foi o e-mail. (11) 98070-1102

**Comment by gmeireles** [comment]
@JON-GAMES Tu escreveu em inglês mesmo?
Eu não tenho celular bro :/

**Comment by JON-GAMES** [comment]
Te mandei um e-mail me responde lá.
Ai ja te mostro o modelo do e-mail.

**Comment by frayzee** [comment]
You have to use an AB like a human would use the web app.

If you get greedy an abuse it you WILL be banned no matter what AB you use.

Never use your main account on an AB.

**Comment by gmeireles** [comment]
Thanks @frayzee

**Comment by michiel2304** [comment]
@JON-GAMES Could you translate your message to english? Or send me a private message if that is possible on this site.

**Comment by n0me1** [comment]
@JON-GAMES Could you please elaborate in English?
@hunterjm have you got any experience in dealing with this?

**Comment by edenhazard7** [comment]
I got banned too :(
I only used it for 5 hours max at 10 RPM
Can someone please help me get my account back?

**Comment by frayzee** [comment]
You have to be really, really stupid to use your main account on a bot.

**Comment by mestesso93** [comment]
i've got ban too! But it's ridiculous, i've use this AB only 2 hours and not every day with 5-6-7 RPM! I've lost 140k credits :(

and, i've got ban when i don't use AB :(

**Comment by JON-GAMES** [comment]
I also just received the ban definitely. :(
The procedure I performed the first time I received the ban and it worked out was to send email and call EA .... I'm trying again I hope it works again.

I used 6rpm I performed for two hours and rested 1 hour ...... Few players and little profit.

**Comment by mestesso93** [comment]
yesterday many players being banned. That's not depends about this AB, but about ALL autobuyers! I think that in this period, when the EA upgrade the players, we must be careful with autobuyer..

**Comment by Daves10** [comment]
I also got banned, and I was only using the AB with 5 RPM for 3 hours with auto stop, 2 or 3 times a day.. only 2-3 players, use 3 hours, stop 4 hours, use 3 hours, stop 4, use 3 and that was that for the day. This seemed to me conservative compared to what most people told here that was their settings.

**Comment by syros1977** [comment]
They banned mine too i guess, i cant enter! They are telling me to contact the ea help support because of some technical problems!! Anybody a clue?

**Comment by syros1977** [comment]
im going to contact the support to ask why they ban me! they need to explain that. do you think they know about that AB? because the bidding and buying was done like a human beeing, so i dont think they figuered that out that it was a AB.

**Comment by frayzee** [comment]
Of course they knew you were using a bot that's why you're banned!! This is the risk we take and it's why we don't use main accounts on bots.

**Comment by syros1977** [comment]
Of course i didnt use my main account!

**Comment by Daves10** [comment]
Using this account I never got error 500 or temporary ban,  so I'm guessing everybody must have been banned...

**Comment by anthonymac** [comment]
sorry to hear guys :( i haven't used the AB in over a week. looking at the settings some of you used, i would  have been banned too :s. Perhaps good to wait until all the winter upgrades are completed?

**Comment by gmeireles** [comment]
Someone else banned?

**Comment by DroiderLinux** [comment]
@gmeireles I was banned too, is there a way to unban the account? 
@JON-GAMES can you explain how did you get your account back?

**Comment by benbenedek** [comment]
Few newbie questions, how do you get an additional account to bot on (don't you need to buy another game)?  And then how would I go about transferring money?
