### ISSUE TITLE
unknown response. unable to login

### ISSUE THREAD

**Issue by zboing** [hunterjm/fifa-autobuyer#148]
When I try to sign in, after I input my text verification code, i get the error "unknown response. Unable to login."  I am able to login to the web app in my browser, or from the android app. Any help is appreciated. 
Platform: PS4
App: Windows FIFA Autobuyer 0.4.2
Notes: I do not have a secondary account
Thanks!

**Comment by mestesso93** [comment]
i've got this error when i receive a permanent ban

**Comment by zboing** [comment]
I do not have a ban.

**Comment by phpBiggs** [comment]
I think the urls of login had been changed.

**Comment by ManikandanGuru** [comment]
Just now downloaded the latest version. Same problem.
0.4.3
Error: unknown response. Unable to login"
Any fix for this?

**Comment by gmeireles** [comment]
![image](https://cloud.githubusercontent.com/assets/1919508/23465208/4a649d60-fe76-11e6-8823-9c8e8e259589.png)

**Comment by hunterjm** [comment]
A fix will be released shortly.  Sorry for the delay.
