### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by rafaelget** [hunterjm/fifa-autobuyer#151]
Anyone else having problems to connect?

I think that they changed something on the login urls.

**Comment by phpBiggs** [comment]
I think you right! 
I also have problem in login!

**Comment by ManikandanGuru** [comment]
Same problem for me.
Can't able to login. Unknown error.

**Comment by frayzee** [comment]
Unfortuantely you have all been banned, take more care and attention next time.

**Comment by ManikandanGuru** [comment]
I am not banned. I am playing it fine on my PS4.
This is the first I am trying to login this program, and it's not logging in.

**Comment by rafaelget** [comment]
I don't think so, I still can access on console, webapp and companion app.

**Comment by losersFocus** [comment]
I can confirm that.
@frayzee is wrong. Login failure is not related to a ban.

**Comment by alodavide** [comment]
I have the same problem. Any solution yet?

**Comment by gmeireles** [comment]
I have the same problem

**Comment by alodavide** [comment]
It seems that fifa has changed few urls. I saw changes in other auto buyer softwares.

**Comment by losersFocus** [comment]
which Other ab software?

Get Outlook for iOS




On Thu, Mar 2, 2017 at 2:07 PM +0100, "Davide Alocci" <notifications@github.com> wrote:












It seems that fifa has changed few urls. I saw changes in other auto buyer softwares.

**Comment by alodavide** [comment]
Look here https://github.com/oczkers/fut/issues/250

**Comment by alodavide** [comment]
here an other : https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/333

**Comment by hunterjm** [comment]
Fix will be released shortly.  Sorry for the delay.  Got really busy at work.  Thanks @alodavide for the references to the other projects.
