### ISSUE TITLE
This project is dead?

### ISSUE THREAD

**Issue by pdejda** [hunterjm/fifa-autobuyer#155]
We can not log on for a long time. It's the end of the program? 

:sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob:

**Comment by phpBiggs** [comment]
Hunterjm, project's devolper, not respoding any issue or chat in Gitter. Something happen, probably.

**Comment by MCKuma** [comment]
He has a new project, he made a new auto buyer for fifa 17 if you'd just check.

**Comment by hoelzlichiller** [comment]
that would be awesome!

**Comment by johnyboy87** [comment]
Has this been resolved yet?

**Comment by phpBiggs** [comment]
Not yet, Johnyboy87. Hunterjm is busy at work, We've got to wait.

**Comment by johnyboy87** [comment]
Roger that, hopefully we don't have to wait to long. Do you know what it is he does out of interest, because it must take some knowledge to create somthing like this..

**Comment by hunterjm** [comment]
The login is fixed.  Will be released shortly.  I'm a Software Engineer professionally as well ;)
