### ISSUE TITLE
Loading loop

### ISSUE THREAD

**Issue by MrManiacc** [hunterjm/fifa-autobuyer#16]
After inputing verification code, it sits on a loop loading forever

**Comment by hunterjm** [comment]
Which branch are you running off of?  All work is currently being done on `develop`.

Once I've cleaned up the bidding logic and written unit test for it, executables will be released to https://github.com/hunterjm/fifa-autobuyer/releases, so keep an eye out there.  Should be by the end of this week.  I just got my code signing certificates setup today.

**Comment by DAYBOY** [comment]
When will this be released mate? Looking forward to it.

**Comment by ErhanBicer** [comment]
Hello, when will the new version be released?

**Comment by hunterjm** [comment]
Closing since there hasn't been an update in a while.
