### ISSUE TITLE
error when run 

### ISSUE THREAD

**Issue by PKostya** [hunterjm/fifa-autobuyer#17]
![image](https://cloud.githubusercontent.com/assets/10392452/21803206/1f0df430-d73a-11e6-999a-895aebec1844.png)

**Comment by hunterjm** [comment]
Which branch are you running? Do you have any other cards in your transfer list?

**Comment by jamessi1989** [comment]
Had the same issue on feature branch. Cleared transfer list and no issue. Think the variable name was different can replicate and check if it is useful.

**Comment by hunterjm** [comment]
Interesting. It feels like you had an item in your transfer list that didn't have a resourceId. It would be good to see the values that created the issue so I can test against it.

When I release I'll add some error checking around it so the whole app doesn't blow up though.

**Comment by jamessi1989** [comment]
Some stack and console if useful. 
[stack.txt](https://github.com/hunterjm/fifa-autobuyer/files/697501/stack.txt)

**Comment by kledac** [comment]
Im getting a similiar error but the error is relatated to the propriety player.price.buy on the watchlist. Is there a way to solve it?

**Comment by hunterjm** [comment]
@kledac, do you have auto update pricing turned off in the settings? There is a setting for it, but turning it off is not yet supported.

**Comment by PKostya** [comment]
@jamessi1989 this error i have when in my transfer list are some players wich i add manual to transfer from ps4

**Comment by kledac** [comment]
@hunterjm Its all on default. I checked and update pricing is on. I debug the object that the call to FUT is returning and I have noticed that the object is always the same.

I tried to remove a player from my watchlist and know Its a blank space and that player got undefined. How do I clean only the player from my localstorage?

**Comment by hunterjm** [comment]
@kledac How do you know that's not him?  Can you do a `JSON.stringify` of that object so I can see what's in `itemData`? I will definitely add more error checking around the bidding overview screen, as that is where most of these errors are occurring.

**Comment by hunterjm** [comment]
Hey guys, I just finished unit testing the bid reducer and found a couple bugs in it.  I think it may have to do with what you are seeing.  Checkout the latest version of `feature/cleanUp` and let me know if you stop running into these problems.

**Comment by kledac** [comment]
@hunterjm Hey, after the pull I still have the same problem =/

Here you go the object.itemData
`{"id":109655578054,"timestamp":1484187177,"formation":"f433","untradeable":true,"assetId":208135,"rating":78,"itemType":"player","resourceId":-1878840057,"owners":0,"discardValue":312,"itemState":"invalid","cardsubtypeid":2,"lastSalePrice":0,"morale":50,"fitness":99,"injuryType":"none","injuryGames":0,"preferredPosition":"CM","statsList":[],"lifetimeStats":[],"training":0,"contract":0,"suspension":0,"attributeList":[{"value":71,"index":0},{"value":71,"index":1},{"value":73,"index":2},{"value":74,"index":3},{"value":71,"index":4},{"value":79,"index":5}],"teamid":1795,"rareflag":0,"playStyle":250,"leagueId":13,"loyaltyBonus":1,"pile":0,"nation":18}"`


The undefined player.price happens on line 83 of Transfers.js.

`warning: item.bidState !== 'highest' && player.price != undefined && item.currentBid < player.price.buy && item.expires > -1,`

That `&& player.price != undefined` I've put there just to stop the red screen of death :p

**Comment by kledac** [comment]
@hunterjm I've just noticed this error also ... maybe they are related:

`bid.js?03b6:156 Error searching auctions Error: Fut api error: {"debug":"","string":"","code":"460","reason":"","request":{"url":"/ut/game/fifa17/transfermarket?type=player&start=0&num=16&definitionId=180819&macr=undefined","options":{"headers":{"X-HTTP-Method-Override":"GET"},"url":"/ut/game/fifa17/transfermarket?type=player&start=0&num=16&definitionId=180819&macr=undefined","method":"POST"}}}
    at next (<anonymous>)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
From previous event:
    at Fut.Methods.search.filter [as search] (eval at <anonymous> (http://localhost:3000/dist/bundle.js:7545:2), <anonymous>:51:19)
    at eval (eval at <anonymous> (http://localhost:3000/dist/bundle.js:10221:2), <anonymous>:11:18)
    at dispatch (eval at <anonymous> (http://localhost:3000/dist/bundle.js:4119:2), <anonymous>:45:18)`

**Comment by hunterjm** [comment]
Should be unrelated. The problem with the first one is a player in your watchlist that is not in your player list on the AB.  The second one is an issue with the API.

I'm probably going to delay releasing publicly since EA has been on a ban spree lately until I can verify the login authentication is as undetectable as possible.

**Comment by kledac** [comment]
@hunterjm No problems. If you want I can help you with testing and reporting that back to you.
I'm studying node, but I'm still learning a lot I don't have the skill to correct and modify things in a meaningful way.

Anyway just let me know and thank you for your awesome work :)

**Comment by jamessi1989** [comment]
![error](https://cloud.githubusercontent.com/assets/19503062/21902627/8dc7f6d0-d8f4-11e6-9df1-1bfd43cf5ace.jpg)
Still seeing this. Sorry if it is to do error already discussed, hopefully it is useful. This is was with latest checkin.

**Comment by hunterjm** [comment]
Can you show me what's in the console error? The source map isn't working in that display. The developer console should have a more helpful error message with line numbers not in `bundle.js`

**Comment by jamessi1989** [comment]
![errorconsole](https://cloud.githubusercontent.com/assets/19503062/21907529/cc7d4a02-d907-11e6-847c-2d7a4847644b.jpg)
![errorconsole2](https://cloud.githubusercontent.com/assets/19503062/21907532/ce366ce8-d907-11e6-9ecf-4472e340840e.jpg)

**Comment by jamessi1989** [comment]
And this one which is unrecoverable.
![errorconsole3](https://cloud.githubusercontent.com/assets/19503062/21907827/24eb7cd0-d909-11e6-8394-2140eacdce1d.jpg)

**Comment by hunterjm** [comment]
Can you click on the arrow dropdown of the `bid/set/watchlist` action and drill down into the `action` object and let me see what's there?

**Comment by jamessi1989** [comment]
Hopefully this helps [logg.txt](https://github.com/hunterjm/fifa-autobuyer/files/702972/logg.txt)

**Comment by hunterjm** [comment]
Unfortunately I need to see what's inside the array in `Object {type: "bid/set/watchlist", watchlist: Array[10]}`

Are you able to right click the object and click "Store as global variable"?  If so, you should see something in the console like `temp1` show up.  If you then type `copy(temp1)` in the console, it will copy the entire value to your clipboard which you can paste here using the insert code tag on top of the comment (looks like "< >")

**Comment by jamessi1989** [comment]
Sure, 
[newlog.txt](https://github.com/hunterjm/fifa-autobuyer/files/703008/newlog.txt) - code tags did not format it at all well.

**Comment by hunterjm** [comment]
Is that the array from `bid/set/watchlist`?  If so, that's totally wrong 😞

**Comment by hunterjm** [comment]
should be fixed in 4079094.  Pull it down and try again.  That was a silly bug 😆

**Comment by jamessi1989** [comment]
Aha, running for over 15 mins now seamlessly. This issue is resolved for me.

**Comment by hunterjm** [comment]
Great. I'll close this ticket out. Feel free to create a new one if there are any other issues you run into, or features you would like to see.
