### ISSUE TITLE
how do I generate EXE?

### ISSUE THREAD

**Issue by marlonespindola** [hunterjm/fifa-autobuyer#178]
how do I generate EXE?

**Comment by marlonespindola** [comment]
@hunterjm is there a command in NPM to generate an exe?

**Comment by hunterjm** [comment]
`npm run package` is what you are looking for.  Note that the app will not be code signed unless you are using the official release.  You might also need to modify and/or remove the auto-update code otherwise whenever I publish a new version, your changes will get overwritten.
