### ISSUE TITLE
Windows 10 Compatibility??

### ISSUE THREAD

**Issue by Albvadi** [hunterjm/fifa-autobuyer#18]
Hi,
first of all, thanks for this magnific project...

It´s possible use this in Windows 10?
I´m using develop branch. I have problems during server startup and, with a workaround, finally start. I do the login correct, but then, I can´t do anything inside the app. I can´t set prices in nowhere and I get errors in console...

I can provide a lot of details if you want...
Thanks!

**Comment by hunterjm** [comment]
A Windows installer will be provided with the official release.
