### ISSUE TITLE
autobuyer hanging

### ISSUE THREAD

**Issue by ambrozy123** [hunterjm/fifa-autobuyer#185]
autobuyer is not updating prices and sniping players
is something changed in webapp code??
do you have the same problem?

**Comment by fredh981** [comment]
mine just gets stuck after it says "updating tradepile" but sometimes it gets to "trying to snipe player" then just gets stuck there. I've deleted everything and reinstalled it but it does nothing :(

**Comment by aelnaggar** [comment]
same here stuck on "trying to snipe player" and doesn't move further :(
