### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Trishift** [hunterjm/fifa-autobuyer#187]
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined

 dispatch(addMessage('log', `${binResponse.auctionInfo.length} BIN found for ${player.name}...`));

There is a bug in line 95. Possible suggestions to fix?

**Comment by marlonespindola** [comment]
For now I ve done with a try catch there... Worked for me

**Comment by Trishift** [comment]
Could you please elaborate on that? I'm not very good with code, it would mean a lot to me. Thanks in advance!

**Comment by Trishift** [comment]
@marlonespindola Could you please help me?

I would appreciate it so much i've been trying to fix it for hours.

**Comment by hunterjm** [comment]
The latest release should work, unless they changed something else.

**Comment by Trishift** [comment]
@hunterjm I believe they may have. 

bid.js:328 Uncaught (in promise) TypeError: Cannot read property 'filter' of undefined(…)

export function relistItems(settings) {
  return async (dispatch, getState) => {
    const state = getState();
    const api = getApi(state.account.email);
    const expired = state.bid.tradepile.filter(i => i.tradeState === 'expired');
    if (expired.length > 0) {
      dispatch(addMessage('log', 'Re-listing expired items...'));
      let relistFailed = false;
      if (settings.relistAll) {
        try {
          const relist = await api.relist();
          if (relist.code === 500) {
            relistFailed = true;
          }
        } catch (e) {
          dispatch(addMessage('error', 'Error attempting to relist all auctions', e));
          relistFailed = true;
        }
      }
