### ISSUE TITLE
Error on Transfers.js

### ISSUE THREAD

**Issue by kledac** [hunterjm/fifa-autobuyer#19]
I'm opening a issue cause I don't know how to solve this and it's still happening on feature/cleanUp.

<img width="1440" alt="captura de tela 2017-01-12 as 22 59 28" src="https://cloud.githubusercontent.com/assets/1036582/21914498/e28386f0-d91a-11e6-8a00-f80feb61efd7.png">

This happens after adding a player and starting to run.

**Comment by hunterjm** [comment]
This is because you have cards that are either in your watch list or transfer list which are not being tracked by the app.  I've pushed up a potential fix in af108a4.  Let me know if that works.

**Comment by hunterjm** [comment]
I very quickly decided I wanted to do it this way instead: ce40f0d

**Comment by kledac** [comment]
I've noticed that I confess that my implementation wasn't as elegant as your LoL

Anyway, I'm getting the Unknow outbid but no errors anymore :P 

Thanks
