### ISSUE TITLE
Login error: Exceeded maxRedirects [...]

### ISSUE THREAD

**Issue by Jeezie** [hunterjm/fifa-autobuyer#195]
Error:
![Error](https://d3higte790sj35.cloudfront.net/images/ae/sz/95197d20f8d006b57978b2aa56554d45.jpeg)

**Comment by marlonespindola** [comment]
It's happening with me too... Any one else??

**Comment by marlonespindola** [comment]
Did you see the warning that is showing now about react package??
![react_warning](https://user-images.githubusercontent.com/16193729/28823639-fbb4727a-7694-11e7-8dd6-e6f229d9e977.jpg)

@hunterjm show we update this package??

**Comment by hunterjm** [comment]
@marlonespindola - no, that shouldn't have anything to do with it.  Have you verified you can login to the web-app fine?

**Comment by marlonespindola** [comment]
@hunterjm yes I'm using the web app normally

**Comment by hunterjm** [comment]
should work in v0.4.7 (#201)

**Comment by marlonespindola** [comment]
@hunterjm I have downloaded the new version, but I still getting the same error message.
should I run any command to update CSS and fut-promisse library here too?

**Comment by marlonespindola** [comment]
@hunterjm done, updated the fut-promise library... now is working
