### ISSUE TITLE
Stuck Updating Price

### ISSUE THREAD

**Issue by dham84** [hunterjm/fifa-autobuyer#196]
I've noticed that the app seems to get stuck when updating prices... seemingly randomly, though I'm sure there's an issue not seen in the app Log.
It doesn't happen with specific players on my list, sometimes it updates one or two and hangs on the third, sometimes it hangs with the first one.

My workaround is to go to the player page and continuously hit Update and toggle between the Bio and Watch tabs until it eventually updates, then I go stop and restart the buyer.

Is there maybe an exception not being handled correctly?

Thanks!

**Comment by ylms** [comment]
It is EA sided, you are getting rate limited.

**Comment by hunterjm** [comment]
#192 may fix this.  It is building now and will release v0.4.6 later today.

**Comment by hunterjm** [comment]
should work in v0.4.7 (#201)
