### ISSUE TITLE
Use typescript/tsx for fifa 18

### ISSUE THREAD

**Issue by DjTrilogic** [hunterjm/fifa-autobuyer#197]
Is it possible to rewrite the code in Typescript for next year's version, I think it'll boost the productivity ...

**Comment by hunterjm** [comment]
Updates for FIFA 18 will probably not need to be made in this project.  The logic for connecting to EA's servers lives in https://github.com/hunterjm/fut-api.  It would be too much effort with little to no benefit for the project to switch to typescript, so likely not something I'm going to take on.
