### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by blumy1** [hunterjm/fifa-autobuyer#198]
Don't use it. It just takes your account data (password etc.). And does nothing.

**Comment by hunterjm** [comment]
Are you a software engineer? Can you read code? Obviously not, since otherwise you would know that the credentials entered are used to authenticate with EA’s web app, but never leave your computer otherwise.

**Comment by blumy1** [comment]
Unfortunately, you are wrong. So tell me why when I give the correct data,
I have an error that I gave wrong secret answer? :)

**Comment by celioreyes** [comment]
@blumy1 b/c you gave the wrong secret answer? 🤔

**Comment by blumy1** [comment]
Funny. Keep going with scamming people.

**Comment by hunterjm** [comment]
So you are telling me you put the same secret into this web app (https://www.easports.com/fifa/ultimate-team/web-app), and it logs you in?

The secret is for the app itself, not your EA account. Many other people have had the same issue if you had just bothered to search.

Now don’t you feel stupid.

**Comment by celioreyes** [comment]
@blumy1 💩
