### ISSUE TITLE
Auto update prices

### ISSUE THREAD

**Issue by Syzak98** [hunterjm/fifa-autobuyer#199]
Hi!
I have an issue with auto update prices... In log everything stops and program does nothing.

![213](https://user-images.githubusercontent.com/30688518/28914572-750f2900-783c-11e7-81b7-7e714b6f74ec.PNG)

**Comment by ylms** [comment]
The dev needs to pull this update;
https://github.com/hunterjm/fifa-autobuyer/pull/192

Otherwise the bot will always stuck on failure.

**Comment by hunterjm** [comment]
Merged in, app should auto-update sometime later today.

**Comment by hunterjm** [comment]
should work in v0.4.7 (#201)
