### ISSUE TITLE
Keep getting "Wrong secret"

### ISSUE THREAD

**Issue by tomtomate** [hunterjm/fifa-autobuyer#203]
Hello.

Ich cant Login to the webapps via this Programm. It keeps telling wrong secret although the secret Code ist right and freshly pasted out of my mail account.
After a few tries i cant use the original webapp as well anymore, and it says that i need to access FIFA ultimate Team via my xbox to Reset my secret question. Somehow i think the secret authenthification Key and the secret question are getting Mixed Up or are there other solutions for ne? Am i doing something wrong.

Regards tomtomate

**Comment by hunterjm** [comment]
The secret for the app is your FUT account’s secret question, NOT your EA account (the web app asks for it after you log in before letting you transfer).

You were probably using the wrong one. Just reset your secret on your console, and use that one next time.
