### ISSUE TITLE
Problem Login Load

### ISSUE THREAD

**Issue by Tobizy** [hunterjm/fifa-autobuyer#204]
Hello first times sorry for my bad english I come from germany I have a problem with the fifa autobuyer if I want to lie in and the two factor code is loading it eternally and does not listen on it now already 10 minutes could they help me please? screenshot is  attached to 

![unbenannt](https://user-images.githubusercontent.com/31143328/29477162-749fc15a-8467-11e7-9aca-1879ce25f4cd.PNG)

**Comment by hunterjm** [comment]
Did you close this because you got it working? What was the problem?

**Comment by Tobizy** [comment]
I was banned had to enter a code in the webapp afterwards it went again because of this I closed it it was probably because I have requested too many security codes LG
