### ISSUE TITLE
When creating the new AUTOBUYER for FIFA 18, please take inspiration from FUTmatebot

### ISSUE THREAD

**Issue by ethansam89** [hunterjm/fifa-autobuyer#208]
www.futmatebot.com has a great autobuyer and allows a free trial. Please take ideas from in to create the new one.

**Comment by ylms** [comment]
This isn't a place where you can advertise your bot.

**Comment by ethansam89** [comment]
It's not my bot bro, I'm 17 and don't know the least bit about coding.

**Comment by marionety** [comment]
Only is needed to update the api, this app should work when it's done.

**Comment by ZakariaAhmed** [comment]
futmatebot, is the worst crap I have ever seen, poor handling even of the two factor auth. 
not even talking about the design either. so yah this post from ethansam is probably an advert

**Comment by ethansam89** [comment]
Well it's actually mad, and I'm not advertising it. But believe what you want. I'm currently using the Mulefactory plugin for it, and have made £100 this week.

**Comment by maxsslob** [comment]
ethansam89, how many accounts do you run? Which platform?

**Comment by ethansam89** [comment]
1 because I haven't unlocked any others yet and on Xbox one.

**Comment by ps4geek** [comment]
Instead of wasting your money on this garbage, there is a superb list of FIFA 18 trading bots on Reddit here: https://www.reddit.com/r/fifa18tradingbot/

**Comment by ghost** [comment]
This page doesn't seem to exist.

Thank you,
Michael O'Mahony
Executive Director
MPC Retail Group Ltd.
________________________________
