### ISSUE TITLE
How it´s works??

### ISSUE THREAD

**Issue by Albvadi** [hunterjm/fifa-autobuyer#23]
Hi,
first of all, thanks for your great work... The UI it´s superb!

I downloaded the windows version, installed correctly without problems and login perfectly.

But now... what?
I can search a player, add to the left sidebar but... I can´t do more steps... or at least, I don´t know wich it´s the next step...
I don´t know how to set the prices, or ranges for any player...

Thanks again!!

**Comment by hunterjm** [comment]
Clicking on a player will pull up their details, as well as pricing information based on settings.
Clicking "Bidding Overview" will bring you to the bid screen, where you can start bidding.
You can also start bidding by clicking the "play" button at the bottom of the left bar.
Clicking the gear icon at the bottom of the left bar will bring you to the settings.

**Comment by Albvadi** [comment]
Hi,
any player I searched, has the same info... all prices are set to 0.

I tryed with the default settings, and lower and upper values, but no changes, always appears 0 in the BIO.

Attach a screenshot with a example...
![autobuyer](https://cloud.githubusercontent.com/assets/6285255/22101684/b72e169a-de34-11e6-8e2f-ad5257b2ebf2.png)

I don´t know whtat it´s failing...

Thanks!
