### ISSUE TITLE
futApiStatusCode": 461

### ISSUE THREAD

**Issue by jamessi1989** [hunterjm/fifa-autobuyer#24]
Perhaps just bid already received from another person.

[21:29:01] Error placing bid on Romero
{
  "futApiStatusCode": 461
}

**Comment by hunterjm** [comment]
I believe that is what code 461 means. I'll keep this issue as a note to clean up logs to make more legible.

**Comment by hunterjm** [comment]
This should be fixed in the next release.  There was an issue with the relist player logic.  See 9967078c62efd33cde5f43b6d100e46f841c380d.
