### ISSUE TITLE
The server with 1 CPU also running very slowly.

### ISSUE THREAD

**Issue by ErhanBicer** [hunterjm/fifa-autobuyer#25]
[![fabhj.jpg](https://s23.postimg.org/fy3pb6wez/fabhj.jpg)](https://postimg.org/image/lma0230rb/)

**Comment by hunterjm** [comment]
What type of processor do you have?  Does the CPU usage go down when not bidding?

**Comment by ErhanBicer** [comment]
@hunterjm 
I run it through Vultr.com's virtual server.. The program is not running because the processor power is high. Can't offer bidding.

**Comment by ErhanBicer** [comment]
There is no problem with the processor when there is no start-up order. But the kernel is overloaded when the initiation command is issued. ( my english is not very good. i hope understandable. )

**Comment by hunterjm** [comment]
The virtual server likely does not have enough resources to run the app.  I am able to run it locally with no resource issues.  Try upgrading the Virtual Server, or running locally.
