### ISSUE TITLE
Build out Global Preferences pane

### ISSUE THREAD

**Issue by hunterjm** [hunterjm/fifa-autobuyer#3]
Preferences that were included in the python version (and their defaults) are as below.  We will need to create a component that has the same preferences and updates our redux state as well as persists them to `userData` to be reloaded on app load.

```
settings = {
  'rpm': 20,
  'minCredits': 1000,
  'maxPlayer': 20,
  'autoUpdate': 0,
  'buy': 0.9,
  'sell': 1,
  'bin': 1.25,
  'snipeOnly': 0,
  'relistAll': 1
}
```

Currently, I have the button that I was going to use to start bidding on the bottom right of the left pane where players are listed, but we can replace that with a preferences button instead.  Still need to figure out where the "start bidder" button should go, but it should be more obvious than in a corner somewhere.

**Comment by erics273** [comment]
still want help with this?

**Comment by hunterjm** [comment]
completed
