### ISSUE TITLE
Since i cant set price settings manually for each card.What basic price settings can i use ?

### ISSUE THREAD

**Issue by OGDiab** [hunterjm/fifa-autobuyer#31]
@hunterjm thank you for this program .big fan of it and the gui is much better than the last one

**Comment by hunterjm** [comment]
The default settings are pretty conservative and should work well in most cases. I would run it with those for a few hours, review the logs, and tweak it from there until you have found something you like.

**Comment by OGDiab** [comment]
@hunterjm thanks for replying so quick but i was messing around with the settings so i dont know the default ones is there any way i can reset them .and what global settings would you recommend to avoid bans

**Comment by hunterjm** [comment]
10 RPM should be safe for a couple hours a day. Wouldn't recommend ever running 24/7. Default price settings are 90/100/110 with auto update enabled.
