### ISSUE TITLE
"futApiStatusCode": 409

### ISSUE THREAD

**Issue by FlareRare** [hunterjm/fifa-autobuyer#32]
[19:56:26] Error manually re-listing player
{
  "futApiStatusCode": 409
}
[19:56:40] Error manually re-listing player
{
  "futApiStatusCode": 409
}
[19:56:55] Error manually re-listing player
{
  "futApiStatusCode": 409
}

it's omnivoid btw

**Comment by hunterjm** [comment]
Reference https://github.com/oczkers/fut/issues/27 - Error 409 occurs when trying to list an item for sale when it is already listed.  Will need to add some additional error checking here.

**Comment by hunterjm** [comment]
fixed in 9967078.  Will be in next release.
