### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Phoenil** [hunterjm/fifa-autobuyer#33]
https://gyazo.com/d5338e38a4adfef5ddc56096805c3c0c

It always says me that. My password has an Uppercase letter, two numbers, and a special char *
I have checked in localstorage the password is fine, i think that there is some problems with the special char in passwords.

**Comment by hunterjm** [comment]
The AB is configured the follow EA's new password rules. If you haven't changed your password in a while, I would recommend doing that.
