### ISSUE TITLE
Any Suggestions

### ISSUE THREAD

**Issue by mestesso93** [hunterjm/fifa-autobuyer#35]
First, thanks so much for this wonderful work @hunterjm. This new program is pretty good and professional! But i think that this program can be better.
So, these are my suggestion:

1. Need features to set price manually. For some players, i win auction at 200 and that players can be sold for 2000 or higher. But i also have in list another player that need 90/100/110.

2. About rpm: i think is better have a function that automatically and randomly change the rpm about some range value. This for emulate a human behaviour. I think the better range is 4/8.

3. (Maybe this function already there automatically) auto stop the bid after a time can we set and resume after a time can we set.

4. If can add consumables and other object, this program can be perfect!

Sorry for my not-excellent english. Thank you! :)

**Comment by hunterjm** [comment]
I'll address these in the same order:

1. It's on the roadmap
2. We already vary the requests between 75% and 125% of the set RPM value.  You should see this reflected in the timestamps on the logs.
3. This is also on the roadmap
4. This is not currently on the roadmap.  I would need a good source to pull all of the consumable IDs and images from.  If you can help find something similar to [EA Sports Database](easports.com/fifa/ultimate-team/database) for consumables, I would be happy to add it.

**Comment by mestesso93** [comment]
thanks for the reply! for the n°4, futbin have a database of consumables. it's not perfect, but it's a begin.. the IDs maybe is a problem...

**Comment by hunterjm** [comment]
see #55, #58, and #57 for updates once work starts on these.
