### ISSUE TITLE
Transfer List and Player List

### ISSUE THREAD

**Issue by RiskTaking** [hunterjm/fifa-autobuyer#36]
Great job!!

I noticed that if I have a player in transfer list that is not listed in players list, it will shows as unknown and it interrupt the application from showing who was sold or sometimes to assign a player to transfer list . It shows in my log the player was sold, but not in the current page.
this what it shows only
[13:18:39] Skipping bidding, adjust settings to enable...
[13:18:39] Removing sold items from tradepile...
[13:18:47] Updating tradepile...

Currently, I only can know if a player was sold by looking to my coins.

**Comment by hunterjm** [comment]
It shouldn't interrupt the AB's bidding process.  The AB just doesn't track those players.  You have the BIN snipe setting enabled, which means that it won't bid on auctions, hence the message in the console.
