### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by Daves10** [hunterjm/fifa-autobuyer#37]
Hello everyone!

First of all thanks hunterjm for the app and make it available.
I'm new to FUT but immediately saw that we could make profit with trading (as in real life..). I used the FIFA mobile app to do it sometimes but one has to work and do other stuff so the profit was not that much. This app will be very helpful for sure.

From what I read on the forums there is a big risk in getting ban. So far one can mitigate that risk by doing things such as:
-Reduce RPM to 4-6 and change it every hour
-Trade a couple of hours. Stop. Do it later again a couple of hours.
Both make sense as one should act as "human" as possible.

I also saw that we should focus on more rare players then let's say Musa or Remy that are more active. Why this? 
Any other strategies that i should keep in mind to avoid (as much as possible) getting banned?

Also which players should I focus more? For now I used a couple of hours and chose La liga players since i have a La liga squad.

Another thing I though about, let me know if this make sense. Couldn't we create another account, use it for trading, then with our main account sell some players above market price and buy them with the second account? Seems a good way to avoid ban (or get ban on the second not-important account).

Thanks for the help!
Regards.

**Comment by Alevale** [comment]
> Another thing I though about, let me know if this make sense. Couldn't we create another account, use it for trading, then with our main account sell some players above market price and buy them with the second account? Seems a good way to avoid ban (or get ban on the second not-important account).

What i know about that is that they are still banning people that does that manually with 2 accounts, it is quite shitty but i got a warning myself when trying to pass coins from one account to the other by putting players in the auction with a very high coin rate... So i would avoid it as much as possible :) 

It's just a soft ban, and a warning, so you wont really get banned unless they really see something fishy or prove that you did actually made it through a COIN web page, but, still i wouldn't risk it and have to prove them that you are using your accounts "legitimately"

**Comment by hunterjm** [comment]
Transferring coins is just as risky as using an AB.  It is definitely on the roadmap along with multi-account support, however.

**Comment by Daves10** [comment]
Ok, I will refrain from doing that. Thanks

I still haven't found a good set of players do to the AB, could you recommend me some? The only one so far that has been trading actively is Iborra.

**Comment by Elf-1** [comment]
I also want to share my own first experiences. I really like the design, it's much better than the previous one, good work @hunterjm!! I've been using the bot to just buy players and use them in my team, not specifically for trading anymore. However, there is no option for me to fill in the prices manually and keep the card afterwards, I have to set the purchase price in the settings around the price I want to buy it for and then cancel the bot after he sniped one, otherwise it will list the card instantly. Setting the price manually was one thing that was better in the previous version, I did not use the price settings at all and now I have to.

**Comment by hunterjm** [comment]
New tickets have been added to address the feature requests here.  See #55 and #58

**Comment by Daves10** [comment]
Thanks man keep it up!
