### ISSUE TITLE
Players are not listed and the list of available items in webapp is growing.

### ISSUE THREAD

**Issue by Fotospecht** [hunterjm/fifa-autobuyer#38]
After some days of testing I observed that sometimes the list of available items is growing and that these players are not listed anymore. 
Instead I would expect that the autobuyer lists them with the prices of the previous pricecheck. The players are in the playerlist so the prices should be known.

The list of available players is growing - this can be seen in the webapp - but not listed. All these players have "no previous transfer infos".

"Same relist price" is switched off in the settings.

**Comment by Fotospecht** [comment]
Listing them manually in the webapp is working fine without errors.

**Comment by Fotospecht** [comment]
This error is written to the logs - however a manually listing in the web app is working fine:

[13:57:47] Manually re-listing 3 players.
[13:58:05] Error manually re-listing player
{
  "futApiStatusCode": 461
}
[13:58:17] Error manually re-listing player
{
  "futApiStatusCode": 461
}

**Comment by hunterjm** [comment]
This will be fixed in the next release.

**Comment by Fotospecht** [comment]
Thanks.

BTW this program is running far more stable than the FutGui Python program.

After a few days of running multiple instances on my Mac I noticed a memory increase on all instances and a restart was necessary. Looking forward for a version that supports multiple logins  :-)
