### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by d3vilsn0w** [hunterjm/fifa-autobuyer#40]
npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v6.5.0/bin/node" "/root/.nvm/versions/node/v6.5.0/bin/npm" "run" "hot-server" "--" "--start-hot"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! fifa-autobuyer@0.1.1 hot-server: `cross-env NODE_ENV=development node --max_old_space_size=4096 -r babel-register server.js "--start-hot"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fifa-autobuyer@0.1.1 hot-server script 'cross-env NODE_ENV=development node --max_old_space_size=4096 -r babel-register server.js "--start-hot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fifa-autobuyer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node --max_old_space_size=4096 -r babel-register server.js "--start-hot"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fifa-autobuyer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fifa-autobuyer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home//public_html/AutoBuyer/npm-debug.log

npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v6.5.0/bin/node" "/root/.nvm/versions/node/v6.5.0/bin/npm" "run" "dev"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! fifa-autobuyer@0.1.1 dev: `npm run hot-server -- --start-hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fifa-autobuyer@0.1.1 dev script 'npm run hot-server -- --start-hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fifa-autobuyer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run hot-server -- --start-hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fifa-autobuyer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fifa-autobuyer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

**Comment by hunterjm** [comment]
If you are not a developer, what you did wrong is try to run the development environment instead of downloading the executable on the releases page that will install the program on your OS.
