### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by shiransavion** [hunterjm/fifa-autobuyer#44]
i login but all the players value is 0 and wen i do start its not doing nothing
i install the setup file i need somthing more?

**Comment by hunterjm** [comment]
What does it say when you login to the web app? Most likely you don't have the transfer market unlocked yet.

**Comment by shiransavion** [comment]
thank you man work great!!!!
but wen i put only to buy now players is can buy now faster?
wen i find somone buy it befor me
thank you!!!
