### ISSUE TITLE
Issue with autobidding

### ISSUE THREAD

**Issue by Benpano** [hunterjm/fifa-autobuyer#50]
I keep getting the error message "FutApistatusCode" : 461
This happens when the AB bids first on a player and fails to continue bidding resulting in just being outbid every time.

**Comment by frayzee** [comment]
Also getting this error.

**Comment by anthonymac** [comment]
it could be because the other person (or bot) bid at the same time your AB did. Oftentimes when I trade manually via the web app or companion, i experience the same thing.

**Comment by demasc** [comment]
Lads, it was happening with me 'cause I had the companion web app opened simultaneously. I closed that and now it's working fine! Try out

**Comment by hunterjm** [comment]
see #24, It's likely the same issue, and will be fixed in the next update.  If you still see it after the app updates itself, please open a new ticket.
