### ISSUE TITLE
Recommended RPM?

### ISSUE THREAD

**Issue by Chronos69** [hunterjm/fifa-autobuyer#60]
So, from the point of view of the Developer... What's the recommended RPM setting to avoid problems? Stay at 10? Could you go higher? Is recommended to go lower?

**Comment by hunterjm** [comment]
It all depends on how long you plan to run the bot. RPM isn't the only thing EA looks at. They also look at RPD (requests per day). If you only plan to run it for 4 hours a day, 10 RPM is fine. If you want to run it longer, then you need to go lower. There is no safe RPM for running 24/7.

You really just have to find what works best for you. I don't really run the AB unless I'm testing new features. I want to test those as fast as possible, so my RPM is usually set to 15, but I run it for no more than an hour.

Easiest thing to do is set an RPM, run the AB and wait to see how long it takes to start getting `500` errors in the logs. Then you know how long you can run it at that setting.

**Comment by hunterjm** [comment]
If somebody wants to try a couple different settings and upload screenshots here as proof for how long it takes at varying RPM, it could be useful for when #58 is built.

**Comment by WillowWillowWillow** [comment]
I dont have the proof (yet), but I'm at 10 rpm and the autobuyer had been going for 8 hours.
I went to school for 8 hours, came back, no 500 errors.

**Comment by anthonymac** [comment]
@WillowWillowWillow how many players do u have in your tradepile?

**Comment by WillowWillowWillow** [comment]
@anthonymac 40, running at 10 rpm, never had a 500 error.

**Comment by PKostya** [comment]
runnning at 25-50 rpm i had '500' error. At now part of FUT  web app functionallity are blocked.(transfermarket)

**Comment by anthonymac** [comment]
@WillowWillowWillow ok thanks for the info. I have been rather conservative w/ 4 players all between 1500-3000 coins. Do you run at least 3 hours/day? 

@PKostya that RPM is way too high. you are now experiencing a ban. Login to fifa on your console and normal app to see if u can restore functionality. could be a temp ban of 24 hours or could be permanent. Stick to around 10 RPM.

**Comment by brunovky** [comment]
Reviving the topic a bit, what would be the recommended RPM limit for single-player sniping?
