### ISSUE TITLE
Buying with old price value

### ISSUE THREAD

**Issue by Nicorad** [hunterjm/fifa-autobuyer#64]
Hello, 

I had a big issue today.

I started using this app yestarday evening for the first time. Works great.
Today, I started the app. It update the player's price.
My first two players are:

Podolski: Old MaxBid (from yesterday evening)->900. Updated to 550/650/750
Gameiro: Old MaxBid (from yesterday evening)->1100. Updated to 750/850/950

Just after the update, the app starting to BIN Snipe Podolski at 900, then list them at the new price.
Same with Gameiro, BIN Snipe at 1100 (and lower for some), then list at the new price.

Few card for each and were sold within 5 minutes, so I lost around 4000 credits in 5 minutes.

Compare to what this app will make me won, I don't care, but I think it's a big issue that have to be fix...

Thanks for your great work!

**Comment by ConnorMann** [comment]
Is there perhaps a way where updating player prices more often could be implemented? The market seems quite volatile at the moment.

**Comment by Nicorad** [comment]
![capture](https://cloud.githubusercontent.com/assets/5977610/22403466/3df0af90-e618-11e6-8a35-ae0f51e4ffd0.PNG)

Hi, 

I try again this morning and did the same with Bolly.

@ConnorMann The problem is not there, because it is happening when the app start, at the first update... But Its a good idea. Currently I'm using the other project and I modify it to update every 40 min...

**Comment by hunterjm** [comment]
This is on the top of my list.  Unfortunately, I also have a day job, so have limited time to dig into this.

**Comment by hunterjm** [comment]
Once the builds pass for #80, I will release a fix for this.

**Comment by hunterjm** [comment]
Fixed in https://github.com/hunterjm/fifa-autobuyer/releases/tag/v0.2.2

**Comment by Nicorad** [comment]
@hunterjm Many thanks for the fix
