### ISSUE TITLE
Can't enter more than 3 digits in custom player price tab

### ISSUE THREAD

**Issue by silverfoxy** [hunterjm/fifa-autobuyer#68]
If I edit the predefined prices in player's last tab, I can't enter more than 3 digits in it.
![screen shot 2017-01-29 at 2 08 20 pm](https://cloud.githubusercontent.com/assets/1313190/22403439/6dd96422-e62c-11e6-8fa1-f02249fa4825.png)

**Comment by silverfoxy** [comment]
Under playersettings.js, maxLength has to be minLength I assume, it is set to 9 for Purchase Price but is limited to 3 for List and Listed BIN Prices.

`<div className="option-value">
                      <input
                        ref={sellInput => (this.sellInput = sellInput)} maxLength="3" name="sell" placeholder="Sell"
                        value={sell} type="text" onChange={this.handlePriceChange.bind(this)} onBlur={this.handlePriceBlur.bind(this)}
                      />
                      <p className="error-message">{this.state.errors.sell}</p>
                    </div>`

**Comment by hunterjm** [comment]
Yeah, I must have missed that one. Will release a patch soon!

**Comment by hunterjm** [comment]
Fixed in v0.2.1
