### ISSUE TITLE
Convert Bid Strategy

### ISSUE THREAD

**Issue by hunterjm** [hunterjm/fifa-autobuyer#7]
Initially, need to convert the bidding strategy from [hunterjm/futgui](https://github.com/hunterjm/futgui/blob/master/core/bid.py) to JavaScript for v0.1.0.  In a future milestone, I want to make the bidding strategy configurable by the user.  I envision a drag and drop type interface loosely linked to the API calls.

**Comment by GETEM5** [comment]
Don't mean to intrude however I have a quick suggestion:

If you send the autobuyer to sleep for five minutes every now and then (I think every 30minutes however this can be checked with simple trial-and-error testing) you can prevent the account from being temporarily market banned and thus allow the autobuyer to run 24/7

**Comment by hunterjm** [comment]
The python version already throws in random sleep intervals, and this one will too.  Unfortunately it isn't as simple as 30 on/5 off.
