### ISSUE TITLE
Player goes to Unassigned instead of Selling

### ISSUE THREAD

**Issue by Daves10** [hunterjm/fifa-autobuyer#70]
Hello,

Every time I snipe Bamba he goes to the unassigned pile rather than selling. So I have to interrupt the app and do it manually.

He{s the only player where this happens. Perhaps because there are 3 versions of him at different clubs?

**Comment by hunterjm** [comment]
Winning players via BIN always sends it to the trade pile. The app will eventually look in the unassigned pile and should automatically list them once it has made its way through your player list.

Try not to interrupt the app next time and just let it do its thing. If an hour has gone by and he is still not listed, let me know.

**Comment by Daves10** [comment]
OK, I left it for 4  hours and still nothing, all Bamba players went to unassigned and stayed there.

All other trades went normally though.

**Comment by Daves10** [comment]
Also if I can leave a suggestion for a future release it would be nice to complement the Auto Stop with an Auto Start with different RPMs. Or be able to create a schedule.
For instance:
Start at 1pm with 7 RPM for 4 hours
Stop for a couple hours
Start 7pm with 6 RPM for 3 hours
Stop 3 hours
etc etc

Thanks!

**Comment by Daves10** [comment]
Final question and then you can close this thread:

Is there any other reason for a 500 error other that temporary ban? I got one this morning when I started the app, but didn't get any message or email. I stopped, then logged in on the console without any problem.
FYI yesterday I used AB for 4 hours with 6-7 RPM for 3 times, morning, afternoon and during the night. So kind of 4 hours, stopped 4 hours, on 4 hours.. etc
I guess I'll start using for less time now maybe a couple of hours.

**Comment by Fotospecht** [comment]
From my experience a 500 is always a temp ban and you will not get any message for this type of ban.

I use 4 rpm and the program runs 24/7 without any ban.
A setting of 5 rpm leads to a temp ban after some time, even if I stop the autobuyer every 7 hours for one hour.

**Comment by Daves10** [comment]
Thanks that's helpful. How long you've been on 24/7 with 4 RPM setting?

**Comment by Fotospecht** [comment]
Since about 1 year with the previous Futgui version.

**Comment by Daves10** [comment]
All right that sounds proof enough :) Do you stop/log out to play?

I'm gonna try those settings (i was using RPM between 5 and 7 randomly). How much would you say is your average daily profit?

**Comment by Fotospecht** [comment]
I'm not using my main account for the autobuyer, so there is no need to log out.
Profit is about 15k/day.

**Comment by Daves10** [comment]
How do you transfer funds, sell players to your secondary account at slightly higher prices?

**Comment by Fotospecht** [comment]
I check futbin for gold IFs with PRP range 21%-40% and I never sell for the max price.
Example is Fabregas IF on PS4 , buy him for 100k and sell him for 150k.

**Comment by Daves10** [comment]
OK I think I got it. Thanks this has been very helpful!

**Comment by hunterjm** [comment]
In v0.3.0, I updated it to check unassigned every 10 cycles.  Let me know if you are still having issues.  I'll go ahead and close this out for now.
