### ISSUE TITLE
kernel_task process CPU load increases on OS X 

### ISSUE THREAD

**Issue by Fotospecht** [hunterjm/fifa-autobuyer#73]
I'm running 6 instances of the autobuyer on my Macbook Air.

After 2-3 days the 'kernel_task' process has very high CPU load - up to 95%.

It helps to log out in the autobuyer windows and login in again, but after a few hours the CPU load is again very high. The only solution is to quit the programs and restart.

As long as the program doesn't support multiple logins, it would be nice if the accounts and playerlists could be stored separately for each instance. This would help to quickly stop and restart the programs and to circumvent the problem.

Would also be interesting so see if the problem also occurs on Windows.

**Comment by hunterjm** [comment]
This should be resolved with #56. I will probably not spend much time digging into this and instead solve these problems with that release.
