### ISSUE TITLE
Buying for more than Max Price

### ISSUE THREAD

**Issue by Daves10** [hunterjm/fifa-autobuyer#74]
Hello, something weird just happened... As you can see from the pictures I just upload the AB decided to buy this player at a price above the Max Price and even above the list price...

![capelle](https://cloud.githubusercontent.com/assets/25257542/22516801/be24bbce-e885-11e6-8138-7abbf2240bc7.PNG)
![capelle2](https://cloud.githubusercontent.com/assets/25257542/22516802/be259bac-e885-11e6-81c8-eca42e951fc7.PNG)
![capelle3](https://cloud.githubusercontent.com/assets/25257542/22516800/be209224-e885-11e6-9a07-f68c49eb6110.PNG)
![capelle4](https://cloud.githubusercontent.com/assets/25257542/22516840/e334f97e-e885-11e6-8f5b-7619dead5388.PNG)

**Comment by hunterjm** [comment]
Yeah, it looks like there are some issues right after a price update that I haven't been able to track down yet.

**Comment by Daves10** [comment]
Ok I didn't see these errors before but yesterday and today is pretty clear. I have lost already some coins and have several players on the selling list at prices lower than the buy price. Of course in the grand scheme of things it's still a small loss compares to the gains but this need an (urgent) fix. Thanks!

**Comment by hunterjm** [comment]
Closing in favor of #64 which was opened before this one.
