### ISSUE TITLE
Error After transaction

### ISSUE THREAD

**Issue by gmeireles** [hunterjm/fifa-autobuyer#75]
Hi!

After completing a transaction the app stop in "updating unassigned" and does does not work anymore. Everytime i need close the app and open again to reset every proccess

![image](https://cloud.githubusercontent.com/assets/1919508/22519258/dc0e0fa8-e896-11e6-8bec-b93dd4873448.png)

Another problem is that I can not do anything if I do not go through the tutorial

![image](https://cloud.githubusercontent.com/assets/1919508/22519365/29db8ecc-e897-11e6-8c0a-ef01b5d5a41b.png)

Sorry for my english

**Comment by hunterjm** [comment]
Do you have someone in your transfer list or watchlist that isn't being tracked by the AB?

You should be able to click "skip" on the bottom left of the tutorial window.

**Comment by gmeireles** [comment]
Hello @hunterjm 
Thanks for ur help
I will try

**Comment by gmeireles** [comment]
@hunterjm 
Skip option worked

The problem in trade still continues

After the app solling Niang i received the message "updating tradepile..."

Then the application does nothing else


![image](https://cloud.githubusercontent.com/assets/1919508/22520012/cea32e18-e899-11e6-9145-79cf5f5f06b5.png)

**Comment by gmeireles** [comment]
After


![image](https://cloud.githubusercontent.com/assets/1919508/22520668/66195f7c-e89c-11e6-8af1-dd77c2b48fe7.png)

**Comment by Daves10** [comment]
Perhaps you have the "BIN snipe only" activated?

**Comment by gmeireles** [comment]
Hi @Daves10 

Now using this option and I have not had so many recurring errors
But sometimes I get error 401

**Comment by hunterjm** [comment]
Error 401 means "Unauthorized" and is usually due to multiple sessions being open for that account.  Are you logged in to the game or the web app at the same time you are trying to run the AB?

**Comment by gmeireles** [comment]
all right @hunterjm so true

**Comment by hunterjm** [comment]
@gmeireles, can this issue be closed?

**Comment by gmeireles** [comment]
Yes ;)
