### ISSUE TITLE
Mad Buy 

### ISSUE THREAD

**Issue by SargentoDaPaz** [hunterjm/fifa-autobuyer#76]
Problem:

Started the FIFA AUTO BUYER, I did not update the players, ADURIZ was to buy for 1800, when I checked the log I was buying BIN for 2500.

Can  add a button to update all players automatically?

**Comment by mestesso93** [comment]
if you have set "same price relist" you must disabled it

**Comment by SargentoDaPaz** [comment]
Nothing activated

**Comment by hunterjm** [comment]
duplicate of #64
