### ISSUE TITLE
Manual price field resets

### ISSUE THREAD

**Issue by drbo0ombay** [hunterjm/fifa-autobuyer#77]
Sometime when trying to enter value for Buy/List/Bin prices they just reset and I have ot re-enter them several times. Anyone else experience this?

**Comment by mestesso93** [comment]
me too.. I think because the autobuyer check status account wheter non-operating. But i'm not sure

**Comment by hunterjm** [comment]
You need to deselect the "Auto Update Price" checkbox on the player page if you do not want the Auto Buyer to reset the prices based on market value.
