### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by WillowWillowWillow** [hunterjm/fifa-autobuyer#78]
Right after logging in, when the first thing I click is the "play" button (to resume bidding) , I then go to skip the tutorial (because the red-pinging node is annoying to constantly watch), the UI breaks, and I can't view players, switch tabs, or do anything but stare at the white screen seen after logging in.

**Comment by Daves10** [comment]
Clear list and start again!

**Comment by WillowWillowWillow** [comment]
That's not the issue i'm getting. The 'clear list' button doesnt even work when I encounter this issue. Although its easily fixed by re-launching and skipping the tutorial before doing anything else, it's still an issue that needs to be looked at.

**Comment by hunterjm** [comment]
@WillowWillowWillow - I can't seem to replicate this.  When I press the play button on the bottom left, it brings me to the Bidding Overview screen.  Afterwards, when I go back to the search screen to click on the tutorial beacon, I am able to press skip and continue using the app just fine.

Can you make a short video showing me what you are doing?

**Comment by WillowWillowWillow** [comment]
I'm actually not even encountering the error anymore, so it seems that it was either that version of the ABer, or just a compatibility error with the way I was launching the ABer, anyways, it seems to be fixed!
