### ISSUE TITLE
Sniping snipes too high prices

### ISSUE THREAD

**Issue by losersFocus** [hunterjm/fifa-autobuyer#85]
![grafik](https://cloud.githubusercontent.com/assets/24375135/22621676/962e136c-eb29-11e6-9761-ba19eb40eff5.png)

The screenshot shows, that a player was sniped for 950 and listed with an initial bid price of 950. 
The player in question had a min bin at this timepoint of 1000.

Algorithm imo does the following wrong (Not hard to guess, but lets keep it tidy):
It snipes the player for 950 because it was cheaper than the min bin (1000). This usually does not happen, since per default the player will be listed with an initial bid price equaling the min bin. In this specific scenario the initial bid price is 0.95 * min bin.

Solution suggestion:
The sniping price should not be the min bin but the list price.

**Comment by WillowWillowWillow** [comment]
I think a BIN snipe price option should be added, that would be cool.

**Comment by hunterjm** [comment]
The snipe price is the same as the buy price. When did this occur?  A fix for this should have been released today. I'm not sure what time zone you are in, but if this happened overnight the update may not have been applied yet.

**Comment by losersFocus** [comment]
I am UTC +1 (23:16 atm). Where can i check my version?


So summarizing the correct behaviour should be in this casse:
Snipe for 850 (Buy price) and sell for 950/1100.

instead of

Snipe for (950) and sell for 950/1100.

**Comment by hunterjm** [comment]
The updates should automatically be installed when you restart the program. If you restart and it still says no updates available in the top, you are on latest version.

And yes, that is the correct logic.

**Comment by losersFocus** [comment]
I restarted several times today and yes, it sais no updates available. 
I am on the latest version.

**Comment by hunterjm** [comment]
should be fixed in v0.3.0, but not verified.  Please let me know.

**Comment by anthonymac** [comment]
this exact issue happened to me after the update, when i ran the AB for the first time. after about 5 mins it returned to normal behaviour

**Comment by hunterjm** [comment]
I've got something else I'm going to try in a bit. Will update here.

**Comment by hunterjm** [comment]
@anthonymac - please try v0.3.1

**Comment by hunterjm** [comment]
Fixed in v0.3.1
