### ISSUE TITLE
Force minimum profit of 50 

### ISSUE THREAD

**Issue by losersFocus** [hunterjm/fifa-autobuyer#86]
![grafik](https://cloud.githubusercontent.com/assets/24375135/22622045/6195ffd6-eb31-11e6-9a4d-0f76beab889c.png)
The picture shows, that a player with a low bin price (300) will be bought for 250 coins. There will be no profit, because EA takes at least 50 coins as "transaction costs" (Please confirm this, i am not 100% sure).
This happens due to the fact, that the configuration of prices works with percentages. If the percentage difference of buy and sell prices is for example 10%, this would mean a profit of 30 (Rounded up to 50) for a player with min bin 300. 

The pricing algorithm should be modified to guarantee a sure profit of 100 no matter in which price range the player is. Though fifa-autobuyer provides the possibility to configure pricing percentages for each player individually, it would be inconvinient.

**Comment by hunterjm** [comment]
That is the responsibility of the user in my opinion. Some players wouldn't ever be able to generate a profit of 100 coins, especially after EA tax of 5% (not 50 coins).

We can make it so the percentage configuration for players is able to be modified on a per-player basis so the auto update still works.

**Comment by hunterjm** [comment]
Also, in the example above, you would still make a 35-82 coin profit.
