### ISSUE TITLE
Problems with bidding,buying, sniping and selling!

### ISSUE THREAD

**Issue by syros1977** [hunterjm/fifa-autobuyer#89]
there are some problems with the price settings! what percentage do you use for the ab? in order of the options i have 90,100,120% ! but i figuered out after a few snipings that the ab sets the players for the same price on the transfer list. which means that you loose coins. the bin price is always as high as my sniping price, same to the other settings! what am i doing wrong, need some help. at the other releases it worked perfect, since 2.something i have these problems!

**Comment by losersFocus** [comment]
I experience inconsitencies with price calculation as well. 
Prices are not correctly calculated. In concrete they are no rounded correctly. 

![grafik](https://cloud.githubusercontent.com/assets/24375135/22628058/60a75394-ebcd-11e6-9ad3-6be3935d9487.png)

My configuration:

![grafik](https://cloud.githubusercontent.com/assets/24375135/22628065/6ef182e4-ebcd-11e6-813d-d86a9e67e0b8.png)


I expect the List Price to be 1750 (0.99 * 1800 = 1782 -- Round --> 1750(RoundUp)/1800(RoundDown))and not 1700

**Comment by hunterjm** [comment]
1750 is not a valid price, so it obviously won't use that. Increments of 50 are only valid for bids less than 1000.

**Comment by hunterjm** [comment]
v0.3.0 should have some more logic to help with ensuring players are bought at the right price.  Let me know if you still encounter any issues with sniping players for too much.

**Comment by hunterjm** [comment]
Found more issues, please try v0.3.1

**Comment by hunterjm** [comment]
Closing, fixed in v0.3.1
