### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by PKostya** [hunterjm/fifa-autobuyer#90]
in master/dev i have some error: 
![image](https://cloud.githubusercontent.com/assets/10392452/22630213/c1fe398a-ec06-11e6-8db2-74171b317238.png)
after removing "@import (inline) '../../node_modules/react-joyride/lib/styles/react-joyride-compiled.css';" in 
app/styles/main.less all is ok

**Comment by hunterjm** [comment]
The build is working in windows Mac and Linux if you look at the CI status, so my guess is you probably need to do another `npm install` as the dependencies have changed but you haven't updated them on your machine.
