### ISSUE TITLE
Automatically refresh session 

### ISSUE THREAD

**Issue by PKostya** [hunterjm/fifa-autobuyer#91]
How i can automatically refresh my session ?

**Comment by hunterjm** [comment]
What do you mean by refreshing your session?  You mean if you do not perform any actions and need to log back in because the session expired?  If so, that will be fixed in v0.3.0

**Comment by PKostya** [comment]
I mean that when i have large rpm all the stops and restarts when i quit-enter in app

**Comment by hunterjm** [comment]
I'm sorry, I don't really understand what you are asking for.

**Comment by atovik** [comment]
i think his talking about the 401 code (session expired. cf screen shoot, im using the 0.4.5 version)...there is any solution plz ?

![capture d ecran 2017-06-29 a 00 30 17](https://user-images.githubusercontent.com/3350505/27663380-61f218dc-5c62-11e7-9bb8-da6ce1184dbc.png)
