### ISSUE TITLE
Not listing BIN players

### ISSUE THREAD

**Issue by drbo0ombay** [hunterjm/fifa-autobuyer#96]
I'm having issues atm with the AB not listing BIN Players, anyone else had this occur?

**Comment by drbo0ombay** [comment]
When I stop and start it again I realized that it updates unassigned and lists the item, which it doesn't do after the BIN is bought.

**Comment by hunterjm** [comment]
As of v0.3.0, it should update unassigned every 10 cycles, as well as right after you snipe someone.  There have been sparse reports of it not working after a snipe, which I haven't been able to verify, but at least now it should do it every 10 cycles through your player list.

This was meant to help with not needlessly checking the unassigned pile and slowing down the AB.  If 10 cycles is too many, we can talk about reducing that.

**Comment by drbo0ombay** [comment]
Oh yea, I can see that now. Really appreciate this by the way!

**Comment by hunterjm** [comment]
No problem.  Let me know if you run into any other issues.
