### ISSUE TITLE
Error placing bid?

### ISSUE THREAD

**Issue by gertjan22** [hunterjm/fifa-autobuyer#97]
[22:27:51] Something happened when trying to bid on *******
[22:27:55] Error placing bid on *********
{
  "futApiStatusCode": 500,
  "reason": ""
}

what is this ? please help

**Comment by hunterjm** [comment]
Usually a temp ban. What RPM settings are you using, and do you have auto stop enabled? It should clear up within 24 hours, but I would decrease your RPM or shorten the amount of time you are running the AB.

How long did you have it running before the 500 errors started showing up? If you want to run 24/7 you should set RPM to 3-4. Previous testing shows 10 RPM to be safe for 6-8 hours before temp ban is issued. Others have reported that you can make 4000-5000 requests per day (hence the 3-4 RPM)

To be safe, I would enable auto stop and have it set to how ever many hours it would take your current RPM settings to hit 4000 requests. so 10 RPM would be max of 6.5 hours.

**Comment by gertjan22** [comment]
i have it on 12 but when i sign in on my ps4 i can make bids on players 
 i have the message 2 hours ago

**Comment by hunterjm** [comment]
You need to wait 24 hours for an to go away.

**Comment by hunterjm** [comment]
You can still bid on console. It's just web app that is banned.
