### ISSUE TITLE
Player bought by BIN not relisted sometimes

### ISSUE THREAD

**Issue by losersFocus** [hunterjm/fifa-autobuyer#98]
![grafik](https://cloud.githubusercontent.com/assets/24375135/22667583/aa611006-ecbd-11e6-804c-099e9feca636.png)

Bought player Kahraba by BIN and it wont be relisted as seen in the image. Just keeps sitting in the unassigned category

**Comment by hunterjm** [comment]
Are you sure that is Kahraba?  It should have shown the name as Kahraba instead of "Unknown".  Can you login to the web app and take a look there to see what it is?

**Comment by topkek5** [comment]
i tried this also yesterday, most of the time the player i bought didn't get listed

**Comment by losersFocus** [comment]
Ok, this problem gets severe now. 
None of my bought players - bought by auction or by bin - are listed anymore. :( :(

**Comment by hunterjm** [comment]
I'll look into it.

**Comment by losersFocus** [comment]
Happens 70% - 100% for buys buy BIN.

**Comment by hunterjm** [comment]
I think this is the same issue as #130, in which case, will be fixed in v0.4.2

**Comment by hunterjm** [comment]
Fix is live
